[package]
name = "llmrc-ollama"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Ollama provider for llmrc"
license.workspace = true

[dependencies]
async-trait.workspace = true
futures.workspace = true
llmrc-core = { path = "../core", version = "0.1.0" }
ollama-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
thiserror.workspace = true
